### ISSUE TITLE
Null values cancel team

### ISSUE THREAD

**Issue by brad-cooley** [acm-mu/acmweb#5]
If there are any null values for teams (shirts, etc.) it cancels the team and does not add them to the database.

**Comment by brad-cooley** [comment]
This is the logic for this: [https://stackoverflow.com/questions/10270446/how-do-i-replace-an-empty-form-field-with-a-0-in-order-to-prevent-nan-in-jquery](url)

I'm not sure where to put it. It seems like it needs to be an on-submit thing.

**Comment by Jl5her** [comment]
The issue has been resolved.
